package model.listener.plugin;

import java.util.Optional;
import model.utility.Vec3f;


public interface Plugin {

    /**
     * Active the audio changes generated by this plug-in. 
     * Keep the configuration if it has been previously disabled.
     */
    void enable();

    /**
     * Deactive the audio changes and restore the default value. 
     */
    void disable();

    /**
     * 
     * @return the state of activity of the plug-in
     */
    Boolean isEnabled();

    /**
     * 
     * @return the type of the plug-in
     */
    PluginType getType();

    /**
     * 
     * @param value
     */
    void setParameters(Parameters value);

    /**
     * 
     * @param type
     * @return
     */
    Optional<Vec3f> getVectValue(PluginType type);

    /**
     * 
     * @param type
     * @return
     */
    Optional<Float> getFloatValue(PluginType type);

}
